# Generated by Django 5.1.5 on 2025-02-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='Загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name=' Укажите описание описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Укажите цену')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('HORROR', 'Horror'), ('COMEDY', 'Comedy'), ('FANTASY', 'Fantasy')], default='HORROR', max_length=10, verbose_name='Выберите жанр')),
                ('time', models.TimeField(verbose_name='укажите время просмотра')),
                ('director', models.CharField(default='Иванов Иван', max_length=100)),
                ('trailer', models.URLField(verbose_name='укажите из YouTube')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.DeleteModel(
            name='FilmModel',
        ),
    ]
